version: '3.8'
services:
  web:
    # build: <chemin_vers_dossier_contenant_dockerfile>
    build: .
    volumes:
      - ./src/reservation_hotel:/app/src/reservation_hotel
    ports:
    # - <HOST_PORT>:<CONTAINER_PORT>
      - 5000:5000
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: reservations_hotels
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: